#include <QtTest>
#include <QDir>
#include <QFile>
#include <QSettings>
#include <QSignalSpy>
#include <QStandardPaths>
#include <QTemporaryDir>

#include "Provisioning.h"
#include "stubserver.h"

// Provisioning detection, ownership, execution, and owned-only lifecycle
// (DD-022..DD-026). enableTestMode() redirects HOME-based paths under a
// temp dir and records external commands instead of running them, so no
// real home directory or system service is ever touched.
class TestProvisioning : public QObject {
    Q_OBJECT
private slots:
    void initTestCase() {
        QStandardPaths::setTestModeEnabled(true);
        QCoreApplication::setOrganizationName(QStringLiteral("lain-test"));
        QCoreApplication::setApplicationName(QStringLiteral("lain-test"));
    }

    void init() {
        QSettings().clear();
        QSettings().sync();
        m_stub = new StubServer(this);
        QVERIFY(m_stub->listen());
        m_prov = new Provisioning(this);
        m_base = new QTemporaryDir();
        QVERIFY(m_base->isValid());
        m_prov->enableTestMode(m_base->path());
    }

    void cleanup() {
        delete m_prov;
        m_prov = nullptr;
        delete m_stub;
        m_stub = nullptr;
        delete m_base;
        m_base = nullptr;
        QSettings().clear();
        QSettings().sync();
    }

    void alwaysOffersServiceAndBinaryFallback() {
        const QVariantList methods = m_prov->methods();
        QStringList ids;
        for (const QVariant &v : methods)
            ids << v.toMap().value("id").toString();
        QVERIFY(ids.contains(QStringLiteral("service")));
        QVERIFY(ids.contains(QStringLiteral("binary")));
    }

    void detectsStubServerHealth() {
        m_prov->probe(m_stub->baseUrl());
        QTRY_VERIFY(!m_prov->probing());
        QVERIFY(m_prov->serverReachable());
        QCOMPARE(m_prov->serverVersion(), QStringLiteral("test-1.0"));
    }

    void recordsOwnedInstances() {
        QVERIFY(!m_prov->owned());
        m_prov->setOwned(QStringLiteral("service"), QStringLiteral("/tmp/lain-test"), QStringLiteral("1.0"));
        QVERIFY(m_prov->owned());
        QCOMPARE(m_prov->ownedMethod(), QStringLiteral("service"));
        m_prov->clearOwned();
        QVERIFY(!m_prov->owned());
    }

    void dockerProvisionWritesComposeAndStarts() {
        QVariantMap params{{"port", 9361},
                           {"dataDir", m_base->path() + QStringLiteral("/data")},
                           {"mediaDir", m_base->path() + QStringLiteral("/media")},
                           {"version", QStringLiteral("v0.1.0")}};
        QSignalSpy done(m_prov, &Provisioning::taskFinished);
        m_prov->provision(QStringLiteral("docker"), params);
        QCOMPARE(done.count(), 1);
        QVERIFY(done.first().first().toBool());
        const QString compose = m_base->path() + QStringLiteral("/.lain/docker-compose.yml");
        QFile f(compose);
        QVERIFY(f.open(QIODevice::ReadOnly | QIODevice::Text));
        const QString text = QString::fromUtf8(f.readAll());
        QVERIFY(text.contains(QStringLiteral("ghcr.io/enrell/lain:v0.1.0")));
        QVERIFY(text.contains(QStringLiteral("\"9361:9360\"")));
        QVERIFY(text.contains(QStringLiteral("Generated by lain-desktop")));
        QVERIFY(m_prov->owned());
        QCOMPARE(m_prov->ownedMethod(), QStringLiteral("docker"));
        QVERIFY(m_prov->executedCommands().join(QLatin1Char('\n')).contains(QStringLiteral("docker compose up -d")));
    }

    void serviceProvisionWritesUnit() {
        QVariantMap params{{"port", 9362},
                           {"dataDir", m_base->path() + QStringLiteral("/data")},
                           {"mediaDir", m_base->path() + QStringLiteral("/media")},
                           {"version", QStringLiteral("v0.2.0")}};
        QSignalSpy done(m_prov, &Provisioning::taskFinished);
        m_prov->provision(QStringLiteral("service"), params);
        QCOMPARE(done.count(), 1);
        QVERIFY(done.first().first().toBool());
        QFile f(m_base->path() + QStringLiteral("/.config/systemd/user/lain.service"));
        QVERIFY(f.open(QIODevice::ReadOnly | QIODevice::Text));
        QVERIFY(QString::fromUtf8(f.readAll()).contains(QStringLiteral("--port 9362")));
        const QString log = m_prov->executedCommands().join(QLatin1Char('\n'));
        QVERIFY(log.contains(QStringLiteral("download https://github.com/enrell/lain/releases/download/v0.2.0/")));
        QVERIFY(log.contains(QStringLiteral("systemctl --user enable --now lain.service")));
        QCOMPARE(m_prov->ownedMethod(), QStringLiteral("service"));
    }

    void refusesLifecycleWhenExternal() {
        QVERIFY(!m_prov->owned());
        QSignalSpy done(m_prov, &Provisioning::taskFinished);
        m_prov->startOwned();
        QCOMPARE(done.count(), 1);
        QVERIFY(!done.first().first().toBool());
        m_prov->stopOwned();
        m_prov->uninstallOwned();
        QCOMPARE(done.count(), 3);
    }

    void dockerLifecycleAndUninstall() {
        QVariantMap params{{"port", 9361},
                           {"dataDir", m_base->path() + QStringLiteral("/data")},
                           {"mediaDir", m_base->path() + QStringLiteral("/media")},
                           {"version", QStringLiteral("v0.1.0")}};
        m_prov->provision(QStringLiteral("docker"), params);
        QVERIFY(m_prov->owned());
        m_prov->clearExecuted();
        m_prov->stopOwned();
        QVERIFY(m_prov->executedCommands().join(QLatin1Char('\n')).contains(QStringLiteral("docker compose down")));
        m_prov->startOwned();
        QVERIFY(m_prov->executedCommands().join(QLatin1Char('\n')).contains(QStringLiteral("docker compose up -d")));
        m_prov->uninstallOwned();
        QVERIFY(!m_prov->owned());
        QVERIFY(!QFile::exists(m_base->path() + QStringLiteral("/.lain/docker-compose.yml")));
        QVERIFY(QDir(m_base->path() + QStringLiteral("/data")).exists());
    }

    void comparesDesktopVersions() {
        QCOMPARE(Provisioning::compareVersions(QStringLiteral("0.1.0"), QStringLiteral("0.2.0")), -1);
        QCOMPARE(Provisioning::compareVersions(QStringLiteral("v0.2.0"), QStringLiteral("0.2.0")), 0);
        QCOMPARE(Provisioning::compareVersions(QStringLiteral("0.2.1"), QStringLiteral("0.2.0")), 1);
        QCOMPARE(Provisioning::compareVersions(QStringLiteral("0.10.0"), QStringLiteral("0.9.3")), 1);
        QCOMPARE(Provisioning::compareVersions(QStringLiteral("1.0"), QStringLiteral("1.0.0")), 0);
    }

    void buildsDesktopAssetUrl() {
        QCOMPARE(Provisioning::desktopAssetUrl(QStringLiteral("v0.2.1")),
                 QStringLiteral("https://github.com/enrell/lain-desktop/releases/download/v0.2.1/"
                                "lain-desktop_0.2.1_linux_x86_64.AppImage"));
    }

    void installsDesktopFileWithIconRefresh() {
        // A fake AppImage (shell script) stands in for the bundle: it must
        // gain the executable bit, land on the target, and refresh the icon.
        const QString fake = m_base->path() + QStringLiteral("/update.AppImage");
        QFile script(fake);
        QVERIFY(script.open(QIODevice::WriteOnly | QIODevice::Text));
        script.write("#!/bin/sh\n"
                     "if [ \"$1\" = \"--appimage-extract\" ]; then\n"
                     "  mkdir -p \"squashfs-root/usr/share/icons/hicolor/256x256/apps\"\n"
                     "  printf \"new-icon\" > \"squashfs-root/usr/share/icons/hicolor/256x256/apps/lain-desktop.png\"\n"
                     "fi\n");
        script.close();
        const QString target = m_base->path() + QStringLiteral("/bin/lain-desktop");
        QVERIFY(m_prov->installDesktopFile(fake, target));
        QFileInfo installed(target);
        QVERIFY(installed.isExecutable());
        QFile icon(m_base->path() +
                   QStringLiteral("/.local/share/icons/hicolor/256x256/apps/lain-desktop.png"));
        QVERIFY(icon.open(QIODevice::ReadOnly));
        QCOMPARE(icon.readAll(), QByteArray("new-icon"));
    }

    void guardsMediaPermissionFixes() {        QSignalSpy done(m_prov, &Provisioning::taskFinished);
        m_prov->fixMediaPermissions(QStringLiteral("/"));
        QCOMPARE(done.count(), 1);
        QVERIFY(!done.first().first().toBool());
        m_prov->fixMediaPermissions(QStringLiteral("relative/path"));
        QCOMPARE(done.count(), 2);
        QVERIFY(!done.last().first().toBool());
        QVERIFY(QDir().mkpath(m_base->path() + QStringLiteral("/media")));
        m_prov->fixMediaPermissions(m_base->path() + QStringLiteral("/media"));
        QCOMPARE(done.count(), 3);
        QVERIFY(done.last().first().toBool());
        QVERIFY(m_prov->executedCommands().join(QLatin1Char('\n')).contains(QStringLiteral("pkexec chown")));
    }

private:
    StubServer *m_stub = nullptr;
    Provisioning *m_prov = nullptr;
    QTemporaryDir *m_base = nullptr;
};

QTEST_GUILESS_MAIN(TestProvisioning)
#include "tst_provisioning.moc"
